language: java
jdk:
  - oraclejdk8
services:
  - docker
addons:
  firefox: "46.0"
before_install:
 - npm install --save selenium-webdriver@2.44.0 
 - npm install selenium-webdriver
 - npm install mocha
 - npm install chai
 - npm install webdriverio
 
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
 - mkdir geckodriver
 - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
 - export PATH=$PATH:$PWD/geckodriver

 - cd '/home/travis/build/YHE54/TestFirefox/caMicroscopeTestSuite'
 - npm install

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  
script:
 - wget "https://raw.githubusercontent.com/YHE54/TestFirefox/master/install.sh"
 - chmod a+x install.sh
 - wget "http://openslide.cs.cmu.edu/download/openslide-testdata/Aperio/CMU-1-Small-Region.svs"
 - wget "https://raw.githubusercontent.com/YHE54/TestFirefox/master/caMicroscopeTestSuite/test1.sh"
 - chmod a+x test1.sh
 - wget "https://raw.githubusercontent.com/YHE54/TestFirefox/master/caMicroscopeTestSuite/selenium-server-standalone-3.0.0-beta4.jar"
 - java -jar ./selenium-server-standalone-3.0.0-beta4.jar&
 - ./node_modules/webdriverio/bin/wdio wdio.conf.js
